// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error("Missing Supabase environment variables. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

const isInvalidRefreshTokenError = (error: unknown) => {
  const message = String((error as { message?: string } | null)?.message ?? "").toLowerCase();
  return message.includes("invalid refresh token") || message.includes("refresh token not found");
};

const getAuthStorageKey = () => {
  try {
    const host = new URL(SUPABASE_URL).host;
    const projectRef = host.split(".")[0];
    return `sb-${projectRef}-auth-token`;
  } catch {
    return null;
  }
};

if (typeof window !== "undefined") {
  void supabase.auth.getSession().then(async ({ error }) => {
    if (!isInvalidRefreshTokenError(error)) return;

    await supabase.auth.signOut({ scope: "local" });

    const storageKey = getAuthStorageKey();
    if (storageKey) {
      window.localStorage.removeItem(storageKey);
    }
  });
}
